import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="w-full h-screen bg-teal-100">
      <Head>
        <title>Ribn Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/topl-placeholder-icon.png" />
      </Head>

      <main className="">
        <div className="text-5xl">
          Ribn Wallet
        </div>
      </main>

      <footer className="">
       
       
      </footer>
    </div>
  )
}
